In [1]:
# Import spacy, import the large english model (this is 600 MB), and disable tagger, ner and lemmatizer.
# Download the large English model ~ 600 MB if you have not done so: `python -m spacy download en_core_web_lg`.
import spacy
nlp = spacy.load('en_core_web_lg',disable=["tagger", "ner", "lemmatizer"])

In [2]:
# Read in the text file with the read_file function.
def read_file(filepath):
    """
    Reads in a text file from the directory and saves the file contents to a variable.
    
    Args:
        text (str): The input text to read and save
        
    Returns: 
        A string containing the file contents.
    """
    with open(filepath) as f:
        str_text = f.read()
    return str_text

## Tokenize and Clean Text

In [3]:
# Use the separate_punc function to remove the puncutation. 
def separate_punc(holmes_text):
    """
    Retrieves all the words in the text without punctuation 

    Args:
        text (str): The input text from which words are extracted witout punctuation.

    Returns:
        list: A list of words

    """
    # Create a list comprehension to get only the tokens, i.e., words in the text.
    return [token.text.lower() for token in nlp(holmes_text) \
            if token.text not in '\n\n \n\n\n!"“”-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n']

In [4]:
# Pass in the first four chapters of Moby Dick to the read_file function.
holmes_text = read_file('Resources/A_Case_Of_Identity.txt')
print(holmes_text)

“My dear fellow,” said Sherlock Holmes as we sat on either side of the
fire in his lodgings at Baker Street, “life is infinitely stranger than
anything which the mind of man could invent. We would not dare to
conceive the things which are really mere commonplaces of existence. If
we could fly out of that window hand in hand, hover over this great
city, gently remove the roofs, and peep in at the queer things which
are going on, the strange coincidences, the plannings, the
cross-purposes, the wonderful chains of events, working through
generations, and leading to the most _outré_ results, it would make all
fiction with its conventionalities and foreseen conclusions most stale
and unprofitable.”

“And yet I am not convinced of it,” I answered. “The cases which come
to light in the papers are, as a rule, bald enough, and vulgar enough.
We have in our police reports realism pushed to its extreme limits, and
yet the result is, it must be confessed, neither fascinating nor
artistic.”

“A cer

In [5]:
# Clean and tokenize the text using the separate_punc function.
tokens = separate_punc(holmes_text)

In [6]:
# Get the length of the tokens list.
len(tokens)

7106

In [7]:
# Look over the tokems to make sure all theo punctuation has been reomved.  
# Some punctuation wasn't removed
print(tokens[:300])

['my', 'dear', 'fellow', 'said', 'sherlock', 'holmes', 'as', 'we', 'sat', 'on', 'either', 'side', 'of', 'the', 'fire', 'in', 'his', 'lodgings', 'at', 'baker', 'street', 'life', 'is', 'infinitely', 'stranger', 'than', 'anything', 'which', 'the', 'mind', 'of', 'man', 'could', 'invent', 'we', 'would', 'not', 'dare', 'to', 'conceive', 'the', 'things', 'which', 'are', 'really', 'mere', 'commonplaces', 'of', 'existence', 'if', 'we', 'could', 'fly', 'out', 'of', 'that', 'window', 'hand', 'in', 'hand', 'hover', 'over', 'this', 'great', 'city', 'gently', 'remove', 'the', 'roofs', 'and', 'peep', 'in', 'at', 'the', 'queer', 'things', 'which', 'are', 'going', 'on', 'the', 'strange', 'coincidences', 'the', 'plannings', 'the', 'cross', 'purposes', 'the', 'wonderful', 'chains', 'of', 'events', 'working', 'through', 'generations', 'and', 'leading', 'to', 'the', 'most', 'outré', 'results', 'it', 'would', 'make', 'all', 'fiction', 'with', 'its', 'conventionalities', 'and', 'foreseen', 'conclusions', 'mo

In [8]:
print(tokens[500:800])

['lid', 'its', 'splendour', 'was', 'in', 'such', 'contrast', 'to', 'his', 'homely', 'ways', 'and', 'simple', 'life', 'that', 'i', 'could', 'not', 'help', 'commenting', 'upon', 'it', 'ah', 'said', 'he', 'i', 'forgot', 'that', 'i', 'had', 'not', 'seen', 'you', 'for', 'some', 'weeks', 'it', 'is', 'a', 'little', 'souvenir', 'from', 'the', 'king', 'of', 'bohemia', 'in', 'return', 'for', 'my', 'assistance', 'in', 'the', 'case', 'of', 'the', 'irene', 'adler', 'papers', 'and', 'the', 'ring', 'i', 'asked', 'glancing', 'at', 'a', 'remarkable', 'brilliant', 'which', 'sparkled', 'upon', 'his', 'finger', 'it', 'was', 'from', 'the', 'reigning', 'family', 'of', 'holland', 'though', 'the', 'matter', 'in', 'which', 'i', 'served', 'them', 'was', 'of', 'such', 'delicacy', 'that', 'i', 'can', 'not', 'confide', 'it', 'even', 'to', 'you', 'who', 'have', 'been', 'good', 'enough', 'to', 'chronicle', 'one', 'or', 'two', 'of', 'my', 'little', 'problems', 'and', 'have', 'you', 'any', 'on', 'hand', 'just', 'now',

## Create Sequences of Tokens

In [9]:
# Organize into sequences of tokens.
# Use 25 words to predict the 26th word using "+1".
train_len = 26 # = 25 training words plus one target word.

# Create an empty list of sequences
text_sequences = []

# Use a for loop to create lists of 26 tokens for the whole text. 
for i in range(train_len, len(tokens)):
    seq = tokens[i-train_len:i]   
    # Add to list of sequences
    text_sequences.append(seq)

In [10]:
# The list of text_sequences should be 26 less than the total tokens.
len(text_sequences)

7080

## Perform Tokenization with Keras

In [11]:
# Import the keras preprocessing text tokenizer from tensorflow to format the data from words into a numerical format.
from tensorflow.keras.preprocessing.text import Tokenizer

2024-07-16 11:26:27.618454: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [12]:
# Initialize the Keras Tokenizer class 
tokenizer = Tokenizer()
# Map each word with an index.
tokenizer.fit_on_texts(text_sequences)

In [13]:
# What is the size of the vocabulary
vocabulary_size = len(tokenizer.word_counts)
print(vocabulary_size)

1596


In [14]:
# Encode each word in the text_sequences to the indices. 
sequences = tokenizer.texts_to_sequences(text_sequences)

## Convert the List of Sequences to Arrays.

In [15]:
# Import numpy to convert the list of sequences to arrays.
import numpy as np

In [16]:
# Convert the all 26 word list of lists to arrays.
num_sequences = np.array(sequences)
# Get the length of the array
len(num_sequences)

7080

In [17]:
print(num_sequences)

[[  35  383  290 ...  619 1588   77]
 [ 383  290   27 ... 1588   77  184]
 [ 290   27  158 ...   77  184   23]
 ...
 [   2  362  610 ...   16   88 1596]
 [ 362  610   19 ...   88 1596    4]
 [ 610   19 1589 ... 1596    4    1]]


## Create input sequences and one-hot encode the target variable.

In [18]:
# Import the to_categorical function to convert the arrays to binary values.
import keras
from keras.utils import to_categorical

In [19]:
# Set the input variable, `X`, to the first 25 numbers of each array.
X = num_sequences[:,:-1]
# Set target variable, `y`, to the last number of each array.
y = num_sequences[:,-1]

In [20]:
# Get the shape of X
print(X.shape)
# Get the length of each sequence.
seq_len = X.shape[1]
print(seq_len)

(7080, 25)
25


In [21]:
# Get the shape of y
y.shape

(7080,)

In [22]:
# Next,one-hot encode the target variable to get transform each index to a binary value. 
# We increase the vocabulary by 1 so we can predict the next word. 
y = to_categorical(y, num_classes=vocabulary_size+1)

In [23]:
# Get the shape of y again.
y.shape

(7080, 1597)

## Creating a LSTM  Model

In [24]:
# Import the dependencies for LSTM model.
import keras
from keras import layers
from keras import ops
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [25]:
def create_model(vocabulary_size, seq_len):
    """
    Create and compile an LSTM-based sequential model for text generation.

    Parameters:
    - vocabulary_size (int): The size of the vocabulary, i.e., the number of unique words in the text.
    - seq_len (int): The length of the input sequences, indicating the number of words in each sequence.

    Returns:
    - model (Sequential): A compiled Keras sequential model for text generation.

    Model Architecture:
    - Embedding Layer: Maps word indices to dense vectors.
    - LSTM Layer 1: 150 units, returns full sequence.
    - LSTM Layer 2: 150 units.
    - Dense Layer: 150 units, ReLU activation.
    - Output Layer: Dense layer with softmax activation for multi-class classification.

    Compilation:
    - Loss: Categorical crossentropy.
    - Optimizer: Adam.
    - Metrics: Accuracy.

    Usage Example:
    ```python
    model = create_model(vocabulary_size=1596, seq_len=25)
    ```
    """
    model = keras.Sequential()
    model.add(keras.layers.Embedding(vocabulary_size, seq_len))
    model.add(keras.layers.LSTM(150, return_sequences=True))
    model.add(keras.layers.LSTM(150))
    model.add(keras.layers.Dense(150, activation='relu'))
    model.add(keras.layers.Dense(vocabulary_size, activation='softmax'))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    # Create a test input with the correct shape
    test_input = ops.ones((1, seq_len))
    # Call the model on the test input
    model(test_input)
    # Generate a summary of the model.
    model.summary()
    return model

## Training the Model

In [26]:
# Define the model and pass in the vocabulary (+1) and the seq_len (25 words).
model = create_model(vocabulary_size+1, seq_len)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (1, 25, 25)            │        39,925 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (1, 25, 150)           │       105,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (1, 150)               │       180,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (1, 150)               │        22,650 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (1, 1597)              │       241,147 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 589,922 (2.25 MB)

 Trainable params: 589,922 (2.25 MB)

 Non-trainable params: 0 (0.00 B)

In [27]:
# Fit model with 290-300 epochs and a batch size of 128.
model.fit(X, y, epochs=300, batch_size=128,verbose=1) 

Epoch 1/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 11s 148ms/step - accuracy: 0.0435 - loss: 6.8868
Epoch 2/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 9s 163ms/step - accuracy: 0.0513 - loss: 6.0690
Epoch 3/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 9s 162ms/step - accuracy: 0.0476 - loss: 6.0198
Epoch 4/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 8s 148ms/step - accuracy: 0.0519 - loss: 5.9630
Epoch 5/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 8s 149ms/step - accuracy: 0.0496 - loss: 5.8646
Epoch 6/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 9s 160ms/step - accuracy: 0.0516 - loss: 5.7445
Epoch 7/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 9s 159ms/step - accuracy: 0.0540 - loss: 5.7390
Epoch 8/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 9s 153ms/step - accuracy: 0.0650 - loss: 5.5350
Epoch 9/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 9s 156ms/step - accuracy: 0.0634 - loss: 5.4581
Epoch 10/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 9s 169ms/step - accuracy: 0.0654 - loss: 5.3981
Epoch 11/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 9s 159ms/step - accuracy: 0.0671 - loss: 5.3464
Epoch 12/300
56/56 ━━━━━━━━━━━━━━━━━━━━ 

In [28]:
# Import the dump function from the pickle module.
from pickle import dump

In [29]:
# Save the model to file
model.save('sherlock_model_300.keras')
# Save the tokenizer
dump(tokenizer, open('sherlock_tokenizer_300', 'wb'))

## Generating New Text

In [30]:
# Import the load function from the pickle module.
from pickle import load
# Import the dependencies needed to load the model and tokenizers, and process the text.
from keras.models import load_model
from keras_preprocessing.sequence import pad_sequences

In [31]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    Generate text using a trained language model.
    
    INPUTS:
     - model: Trained language model (e.g., LSTM) capable of text generation.
     - tokenizer: Tokenizer that was fit on text data.
     - seq_len: Length of the training sequences used to train the model.
     - seed_text: A raw string text serving as the seed for text generation.
     - num_gen_words: The number of words to be generated by model.
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        # Pad sequences to our trained rate of 25 words.
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        # Predict Class Probabilities for each word
        pred_w = model.predict(pad_encoded, verbose=0)[0]
        
        pred_word_ind = np.argmax(pred_w, axis= -1)
        
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

In [32]:
# Choose a 26 word text string from the first four chapters of Moby Dick.
# If less than 26 the accuracy is off. 
text = """Her jacket was black, with black beads sewn
upon it, and a fringe of little black jet ornaments. Her dress was
brown, rather darker than"""

In [33]:
# Create tokens by using the separate_punc function.
text_tokens = separate_punc(text)
print(text_tokens)
# Join the tokens and set them to the "seed_text" variable. 
seed_text = ' '.join(text_tokens)
print(seed_text)

['her', 'jacket', 'was', 'black', 'with', 'black', 'beads', 'sewn', 'upon', 'it', 'and', 'a', 'fringe', 'of', 'little', 'black', 'jet', 'ornaments', 'her', 'dress', 'was', 'brown', 'rather', 'darker', 'than']
her jacket was black with black beads sewn upon it and a fringe of little black jet ornaments her dress was brown rather darker than


In [35]:
# Set the model to the saved trained 300 epoch model. 
model = load_model('sherlock_model_300.keras')
# Set the tokenizer to the trained tokenizer from the model. 
tokenizer = load(open('sherlock_tokenizer_300', 'rb'))

In [36]:
# Call the generate_text function and pass in the required parameters. We set the num_gen_words =50. 
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=25)

'coffee colour at the gallows the case and said her into an armchair he looked her own opinion is then it is a subject in'